#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=98
#..................................................................

USE_PROCD=1
#......procd......

BIN_PATH="/usr/bin/COAP"

start_service() {
    procd_open_instance
    procd_set_param respawn
    procd_set_param command "$BIN_PATH"

    procd_close_instance
}

stop_service() {
    rm -f /var/run/COAP.pid
}

restart() {
    stop
    start
}


